
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microserives-security-realm
          #jwk-set-uri: http://localhost:8181/realms/master


server:
  port: 9000
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/docs

