
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3307/order-service
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8083


springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/docs
    urls[0]:
      url: /aggregate/order-service/v3/api-doc
      name: Order service
