
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/product-service?authSource=admin
server:
  port: 8082

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api/docs
    urls[0]:
      url: /aggregate/product-service/v3/api-doc
      name: Product service
